################
# IMAGE TO BUILD

FROM node:18.19.0-bullseye-slim

WORKDIR /home/node/app

COPY package.json .
COPY yarn.lock .

RUN yarn install  --frozen-lockfile

# COPY ./.storybook ./.storybook
COPY ./app ./app
COPY ./static ./static
COPY ./stories ./stories

RUN yarn build-storybook \
  --quiet \
  --output-dir _build-storybook \
  --config-dir node_modules/@coko/storybook/src/config

##############
# IMAGE TO RUN

FROM node:18.19.0-bullseye-slim

RUN apt-get update && apt-get install -y
RUN npm install --global http-server

USER node

COPY --from=0 /home/node/app/_build-storybook ./_build

CMD ["npx", "http-server", "-p", "8080", "./_build"]
